### ISSUE TITLE
Unable to import s3 records 

### ISSUE THREAD

**Issue by Double-O-ren** [LPM-HMS/GenomeKey2#1]
I get this error: 
```
(ve)genomekey@master:/genomekey/ngxbio$ genomekey -d germline -n 'test_sureselect_5_5' ngx_test_1.tsv --target_bed sureselec
tV_5.5_covered.bed
/home/genomekey/projects/GenomeKey/ve/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:800: UserWarning: SQLAL
CHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppre
ss this warning.
  warnings.warn('SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Se
t it to True to suppress this warning.')
Resuming <Execution[2] test_sureselect_5_5>.  All non-successful jobs will be deleted, then any new tasks in the graph will
be added and executed.  Are you sure? [n]|y: y
INFO: 2015-11-04 18:41:37: Resuming <Execution[2] test_sureselect_5_5>
KeyError('path',)
> /home/genomekey/projects/GenomeKey/genomekey/workflows/germline/util.py(21)parse_inputs()
     20             f = lambda p: p if p.startswith('s3://') else os.path.abspath(p)
---> 21             yield d.pop('path'), d
     22

ipdb> 
```
tsv file: 
```
sample_name     read_pair       chunk   library platform_unit   platform        rgid    path                       
Oren_schaedel      1       1       LB      PU      ILLUMINA        RG1     s3://data.ngxbio.com/u000061/wo-00000144/1004021437-nice-ame/1004021437_NICE_AME/150204_H2W2JCCXX_1004021437_NICE_AME_L008_R1.fastq.gz
Oren_schaedel      2       1       LB      PU      ILLUMINA        RG1     s3://data.ngxbio.com/u000061/wo-00000144/1004021437-nice-ame/1004021437_NICE_AME/150204_H2W2JCCXX_1004021437_NICE_AME_L008_R2.fastq.gz
```
bed files are from Agilents' SureSelect_v5.5

**Comment by egafni** [comment]
dont think you pasted

**Comment by Double-O-ren** [comment]
I pasted it, any updates?

**Comment by yassineS** [comment]
@Double-O-ren The error is simply due to the fact that your tsv is not correctly formated, in fact there are no \t cararters in it. Just use this should solve the problem:
```
sample_name	read_pair	chunk	library	platform_unit	platform	rgid	path
Oren_schaedel	1	1	LB	  PU	ILLUMINA	RG1	s3://data.ngxbio.com/u000061/wo-00000144/1004021437-nice-ame/1004021437_NICE_AME/150204_H2W2JCCXX_1004021437_NICE_AME_L008_R1.fastq.gz
Oren_schaedel	2	1	LB	  PU	ILLUMINA	RG1	s3://data.ngxbio.com/u000061/wo-00000144/1004021437-nice-ame/1004021437_NICE_AME/150204_H2W2JCCXX_1004021437_NICE_AME_L008_R2.fastq.gz
```
Make sure to not copy from the rendered markdown, but rather from the source of this comment.

I tested the 'raw' text of your tsv, the columns are mis-seperated.

**Comment by egafni** [comment]
Oops, sorry Oren github didn't email me your TSV file

I think @yassineS is correct

@yassineS have you been getting genomekey v2 running?  I've setup a micro instance for @Double-O-ren that has a "GenomeKeyDeploy" setup.  It's an always-running instance with a versioned setup of StarCluster/StarClusterExtensions/GenomeKey which provides a reproducible and versioned way to launch GenomeKey clusters.  If you want me to setup something similar on LPM's account LMK.

**Comment by yassineS** [comment]
@egafni I got it to go through the toy example, but no further testings (few things came up).
I don't feel the need of an always-running instance for now, as we don't have loads of data to take care of. But I think if you can make an AMI of the instance will come very handy.

**Comment by egafni** [comment]
Okay LMK when you need it and i'll make an AMI of orens (there will probably be updates between now and then)

**Comment by Double-O-ren** [comment]
@yassineS, thanks, that fixed the error. 
I'm getting another error, Ill open another ticket.
