### ISSUE TITLE
ERROR:  <Task[129] Copy_Target_Bed()> has failed too many times

### ISSUE THREAD

**Issue by Double-O-ren** [LPM-HMS/GenomeKey2#2]
running: 
`
genomekey -d germline -n 'Test_sureselectv5_5_trial_2' ngx_test_2.tsv --target_bed sureselectV_5_5_covered.bed
`

**Comment by egafni** [comment]
specify the full path to the bed

**Comment by Double-O-ren** [comment]
this worked once the full path is specified
