### ISSUE TITLE
ERROR:  <Task[158] Fastqc(library='LB', sample_name='...')> has failed too many times

### ISSUE THREAD

**Issue by Double-O-ren** [LPM-HMS/GenomeKey2#3]
running: 
`
genomekey -d germline -n 'Test_sureselectv5_5_trial_2' ngx_test_2.tsv --target_bed sureselectV_5_5_covered.bed
`
The files are not copied over from S3.

**Comment by Double-O-ren** [comment]
This is due to the state of the S3 file - Glacier. AWS throws a silent error if the file is in Glacier 
-- can close

**Comment by egafni** [comment]
I'm going to leave it open until I add some code t
